version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: yarn dev
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development